project:
  type: website
  output-dir: /docs
website:
  title: "SunCloud Sunny Yun Zhao"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sunny-netizen
      #- icon: twitter
       # href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css

editor: visual

